image: alpine/latest

packages:
  - nodejs
  - npm
  - rsync
  - openssh-client-default

environment:
  site: start.m1n.land

secrets:
  - 2d681c1b-dc07-4222-9d9a-599ec1f3dadc # SSH_DEPLOY_KEY

tasks:
  - build: |
      cd $site
      npm ci
      npm run build
  - deploy: |
      cd $site
      set +x
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_rsa >/dev/null 2>&1
      mkdir -p ~/.ssh && echo "pgs.sh ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE9mZWAJS8RCjMI6Fq7Y4Jr7Kwo3Wqa6guG6N2ptV+i" >> ~/.ssh/known_hosts
      rsync --delete -rv ./dist/ pgs.sh:/start-m1n-land
      set -x

triggers:
  - action: email
    condition: failure
    to: ~m1n/git.sr.ht
