image: alpine/latest

packages:
  - nodejs
  - npm
  - rsync
  - openssh-client-default

environment:
  site: start.m1n.land

secrets:
  - 2d681c1b-dc07-4222-9d9a-599ec1f3dadc # SSH_DEPLOY_KEY

tasks:
  - build: |
      cd $site
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun install
      bun run build
  - deploy: |
      cd $site
      set +x
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_rsa >/dev/null 2>&1
      mkdir -p ~/.ssh
      ssh-keyscan pgs.sh >> ~/.ssh/known_hosts 2>/dev/null
      rsync --delete -rv ./dist/ pgs.sh:/start-m1n-land
      set -x

triggers:
  - action: email
    condition: failure
    to: ~m1n/git.sr.ht
